# Generated by Django 3.2.7 on 2021-09-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x1', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
