# Generated by Django 3.2.7 on 2021-10-04 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptask', '0002_mynumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyNumber',
        ),
    ]
