# Generated by Django 3.2.7 on 2021-10-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210921_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.PositiveIntegerField(null=True)),
                ('b', models.PositiveIntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'MyNumber',
            },
        ),
    ]
