# Generated by Django 3.2.7 on 2021-10-06 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_mynumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mynumber',
            options={'verbose_name_plural': 'Mynumber'},
        ),
    ]
