# Generated by Django 3.2.7 on 2021-10-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_mynumber_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyNumber',
        ),
    ]
