# Generated by Django 3.2.7 on 2021-10-16 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('complete', models.BooleanField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.result')),
            ],
        ),
    ]
