# Generated by Django 3.2.7 on 2021-10-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_inputentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InputEntry',
            new_name='Item',
        ),
    ]
